if [ -f ~/.zshrc ];
then
    source  ~/.zshrc;
fi

if [ -f ~/.aliases ];
then
    source ~/.aliases
fi

export PATH="$PATH:$HOME/bin:$HOME/.local/bin"

# Required for GPG, might be MacOS issue
export GPG_TTY=$(tty)

# Path to where I store my dotfiles config
export DOTDROP_YAML=$HOME/dotfiles/config.yaml

# Setup pyenv
export PYENV_ROOT="$HOME/.local/pyenv"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
