#!/usr/bin/env sh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export DOTDROP_CONFIG="$XDG_DATA_HOME/dotfiles/config.yaml"
#export GIT_CONFIG="$XDG_CONFIG_HOME/git/gitconfig"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export GOPATH="$XDG_DATA_HOME/go"

# Export
export PATH="$PATH:$HOME/bin:$HOME/.local/bin:/$HOME/.cargo/bin:${GOPATH}/bin:$XDG_DATA_HOME/fnm"

# Required for GPG, might be MacOS issue
export GPG_TTY=$(tty)

# EDITOR and VISUAL must go after sourcing
export EDITOR=lvim
export VISUAL=lvim

# Setup pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Setup fnm
eval "$(fnm env --use-on-cd)"

# Source other files
[ -f "$XDG_CONFIG_HOME/aliases/main.sh" ] && . "$XDG_CONFIG_HOME/aliases/main.sh"
