#!/usr/bin/env zsh


# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export DOTDROP_CONFIG="$XDG_DATA_HOME/dotfiles/config.yaml"
#export GIT_CONFIG="$XDG_CONFIG_HOME/git/gitconfig"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export GOPATH="$XDG_DATA_HOME/go"

# Export
export PATH="$PATH:$HOME/bin:$HOME/.local/bin:/$HOME/.cargo/bin:${GOPATH}/bin"

# Required for GPG, might be MacOS issue
export GPG_TTY=$(tty)


# Source files
if [ -f ~/.zshrc ];
then
    source  ~/.zshrc;
fi

if [ -f ~/.aliases ];
then
    source ~/.aliases
fi


# EDITOR and VISUAL must go after sourcing
export EDITOR=nvim
export VISUAL=nvim

# Setup pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Setup nvm
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
