items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  name: theme2
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#191919"
    red: "#eb3d51"
    green: "#66b61a"
    yellow: "#d98e1d"
    blue: "#23ffa8"
    magenta: "#ff00da"
    cyan: "#68a783"
    white: "#eaeaea"
  bright:
    black: "#484848"
    red: "#be6262"
    green: "#4b8a10"
    yellow: "#e5d95e"
    blue: "#23aaff"
    magenta: "#ab005b"
    cyan: "#bbcd81"
    white: "#bbbbbb"
theme: Theme2
